<a href="https://colab.research.google.com/github/saurav11sarkar/Python/blob/main/task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [ ]:
# code here
import numpy as np
a = np.random.randint(0,100,12).reshape(3,4)
print(a)
np.sort(a)

[[19 33 67 65]
 [48 31 40 87]
 [64  5 70 85]]


array([[19, 33, 65, 67],
       [31, 40, 48, 87],
       [ 5, 64, 70, 85]])

In [ ]:
a[a[:,1].argsort()]

array([[64,  5, 70, 85],
       [48, 31, 40, 87],
       [19, 33, 67, 65]])

In [ ]:
a[np.flip(a.max(axis=1).argsort())]

array([[48, 31, 40, 87],
       [64,  5, 70, 85],
       [19, 33, 67, 65]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
# code here
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
x = np.array([41, 87, 72, 36, 92])
marks = np.column_stack((marks,x))
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [ ]:
x1 = np.array([77,83,98,95,89])
x2 = np.array([92,93,99,95,88])

marks = np.vstack((marks,x1,x2))
marks

array([[13, 10,  9, 33, 43],
       [63, 46, 90, 42, 45],
       [39, 76, 13, 29, 67],
       [82,  9, 29, 78, 89],
       [67, 61, 59, 36, 90],
       [77, 83, 98, 95, 89],
       [92, 93, 99, 95, 88]])

In [ ]:
marks = np.column_stack((marks,marks.sum(axis=1)))
marks

array([[ 13,  10,   9,  33,  43, 108, 216],
       [ 63,  46,  90,  42,  45, 286, 572],
       [ 39,  76,  13,  29,  67, 224, 448],
       [ 82,   9,  29,  78,  89, 287, 574],
       [ 67,  61,  59,  36,  90, 313, 626],
       [ 77,  83,  98,  95,  89, 442, 884],
       [ 92,  93,  99,  95,  88, 467, 934]])

In [ ]:
marks[marks[:,-1].argsort()[::-1][:2]]

array([[ 92,  93,  99,  95,  88, 467, 934],
       [ 77,  83,  98,  95,  89, 442, 884]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [3]:
# code here
import numpy as np
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
print(np.unique(arr,axis=1))
print(np.unique(arr,axis=0))

[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [8]:
# code here
a = np.arange(1,17).reshape(8,2)
a
np.flip(a)

array([[16, 15],
       [14, 13],
       [12, 11],
       [10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [11]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
x = 6
np.where(np.any(arr>x,axis=1))[0]

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


# These arrays are given.


In [17]:
# code here
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
np.concatenate((arr1,arr2,arr3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [22]:
# code here
np.random.seed(400)
arr = np.random.randint(100,1000,200).reshape((1,200))
arr[arr != np.min(arr)]
arr[arr != np.max(arr)]

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
       244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
       270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [31]:
# code here
arr = np.random.randint(100,700,10)
arr[arr < 100] = 100
arr[arr > 200] = 200
a = np.sort(arr)
a

array([103, 110, 129, 197, 200, 200, 200, 200, 200, 200])

In [32]:
np.cumsum(a)

array([ 103,  213,  342,  539,  739,  939, 1139, 1339, 1539, 1739])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [39]:
# code here
arr = np.random.rand(10)
arr = np.round(arr,3)
arr
mimi = np.percentile(arr,0)
maxi = np.percentile(arr,100)
p50 = np.percentile(arr,50)
p51 = np.percentile(arr,51)
diff = p51 - p50
diff

0.0027000000000000357

In [38]:
import numpy as np

arr = np.random.rand(10)
arr = np.round(arr, 3)

min_val = np.percentile(arr, 0)
max_val = np.percentile(arr, 100)
p50_val = np.percentile(arr, 50)
p51_val = np.percentile(arr, 51)

diff = p51_val - p50_val

print(f"Rounded array: {arr}")
print(f"Minimum value: {min_val}")
print(f"Maximum value: {max_val}")
print(f"Difference between 51st and 50th percentiles: {diff}")


Rounded array: [0.564 0.074 0.449 0.519 0.63  0.066 0.11  0.768 0.229 0.715]
Minimum value: 0.066
Maximum value: 0.768
Difference between 51st and 50th percentiles: 0.006300000000000028
