<a href="https://colab.research.google.com/github/saurav11sarkar/Python/blob/main/Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
import numpy as np

# Creating a NumPy array 'x' filled with zeros of length 10
x = np.zeros(10)

# Modifying the fifth value (index 4, considering zero-based indexing) of the array to 1
x[4] = 1

# Printing the updated array 'x' after modifying the fifth value
print(f"The updated array is: {x}")


The updated array is: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
import numpy as np

# Prompting the user to input two numbers 'a' and 'b'
a = int(input("Enter the value of 'a': "))
b = int(input("Enter the value of 'b': "))

# Generating a random array of shape (a, b) using NumPy
arr = np.random.rand(a, b)

# Printing the generated array
print(f"The generated array of shape ({a}, {b}) is:\n{arr}")

# Calculating the average of the array
avg = np.mean(arr)

# Printing the average of the array
print(f"\nThe average of the array is: {avg}")


Enter the value of 'a': 3
Enter the value of 'b': 4
The generated array of shape (3, 4) is:
[[0.47920608 0.31223328 0.29320368 0.52026731]
 [0.35279884 0.26468275 0.54008462 0.44058877]
 [0.89420487 0.35525026 0.48547123 0.65771547]]

The average of the array is: 0.4663089298498863


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
import numpy as np

def create_array(a, b):
    # Creating a NumPy array 'x' filled with ones of shape (a, b)
    x = np.ones((a, b)).astype(int)

    # Modifying the border elements of the array to 1 and inner elements to 0
    x[1:-1, 1:-1] = 0

    # Returning the modified array
    return x
create_array(4, 4)


array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
import numpy as np
x = np.linspace(0, 1, 12, endpoint=True)[1:-1]

# Printing the array 'x' that was created
print(f"The generated array is: {x}")


The generated array is: [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
import numpy as np

# Creating an identity matrix of shape (3, 4) using NumPy's identity function
identity_matrix = np.identity(4)[:3]

# Printing the identity matrix
print(f"The identity matrix of shape (3, 4) is:\n{identity_matrix}")


The identity matrix of shape (3, 4) is:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
import numpy as np
x = np.zeros((5, 5))
x += np.arange(5)

# Printing the generated array
print(f"The generated array is:\n{x}")


The generated array is:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
import numpy as np

# Creating a random integer vector 'vec' of shape (10, 2) with values ranging from 1 to 100
vec = np.random.randint(1, 101, size=(10, 2))

# Creating a point 'p' with random integer values ranging from 1 to 100
p = np.array([2,3])

# Calculating the Euclidean distance between each point in 'vec' and the point 'p'
distances = np.sqrt(np.sum((vec - p) ** 2, axis=1)).astype(int)

# Printing the array of distances
print(f"The array of distances is: {distances}")


The array of distances is: [ 66  57  48  53  88 111 104  41  86  13]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
import numpy as np

# Creating a NumPy array of shape (6,7,8)
arr = np.zeros((6,7,8))

# Finding the index (x,y,z) of the 100th element
index = np.unravel_index(99, arr.shape)

# Printing the index (x,y,z)
print(f"The index (x,y,z) of the 100th element is: {index}")


The index (x,y,z) of the 100th element is: (1, 5, 3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
import numpy as np
def reversed_array(n):
  n = n.split()
  n = np.array(n,dtype=float)
  x = n[::-1]
  print(x)

x = input()
reversed_array(x)

1 2 3 4 5
[5. 4. 3. 2. 1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
def count_array(n):
  count = 0
  x = np.array(n)
  for i in x:
    count += 1
  print(f"element_count : {count}")

x = [1,2]
count_array(x)

element_count : 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
import numpy as np
def softmax(z):
    z = np.array(z)
    if z.ndim != 1:
        raise ValueError("Input must be a 1D numpy array")

    e_z = np.exp(z - np.max(z))
    return e_z / np.sum(e_z)

x = [33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278]
softmax(x)

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
def vertical_stack(*args):
  for i in args:
    if not isinstance(i,np.ndarray):
      raise ValueError("All input must be numpy array")
  x = np.vstack(args)
  return x

a= np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])
b= np.array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]])
c= np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

vertical_stack(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
import numpy as np
from datetime import datetime, timedelta

def date_array(start, end):
    # Check if inputs are strings
    if not isinstance(start, str) or not isinstance(end, str):
        raise ValueError("Both inputs must be strings")

    # Convert input strings to datetime objects
    start_date = datetime.strptime(start, '%Y-%m-%d')
    end_date = datetime.strptime(end, '%Y-%m-%d')

    # Check if start date is before end date
    if start_date > end_date:
        raise ValueError("Start date must be before end date")

    # Create numpy array of dates between start and end dates
    num_days = (end_date - start_date).days + 1
    date_array = np.array([datetime.strftime(start_date + timedelta(days=i), '%Y-%m-%d') for i in range(num_days)])

    return date_array

start = '2020-11-25'
end = '2020-11-30'
print(date_array(start,end))

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
import numpy as np
martex = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
martex_mean = martex - np.mean(martex,axis=1,keepdims=True)
print(martex_mean)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[:,[0,1,2]] = arr[:,[2,0,1]]
print(arr)

[[3 1 2]
 [6 4 5]
 [9 7 8]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here
arr = np.arange(1,11)
arr[arr%2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
x = np.sum(a)
y = np.sum(b)
if x < y:
  print(b)
else:
  print(a)

np.maximum(a,b)

[6 3 1 5 8]


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [ ]:
#Code here
arr1 = np.random.randint(1,1000,40).reshape(5,8)
normalizad = (arr1-np.min(arr1))/(np.max(arr1)-np.min(arr1))
print(normalizad)

[[0.98990918 0.20383451 0.05247225 0.20383451 0.50050454 0.77093845
  0.07063572 0.72452069]
 [0.83652876 0.25933401 0.43592331 0.51866801 0.63572149 0.19273461
  0.08678103 0.16145308]
 [0.94651867 0.56609485 0.67507568 0.92633703 0.08173562 0.55701312
  0.99697275 0.95862765]
 [0.95156408 0.39858729 0.42885974 0.93642785 0.92230071 0.54187689
  0.         0.52270434]
 [0.75479314 0.56004036 0.59737639 0.34308779 0.49949546 0.9667003
  0.09586276 1.        ]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [3]:
#Code here
import numpy as np
def argument(arr,n):
  if n <= len(arr):
    sorat_arr = np.sort(arr)[::-1]
    return sorat_arr[n-1]
  else:
    print("Error: n should be less than or equal to the length of the array.")
    return None

arr1 = np.array([12,34,40,7,1,0])
n = 3

argument(arr1,n)


arr2=(12,34,40,7,1,0)
np.array(arr2)
n = 1

argument(arr2,n)

40

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here